; CGA video card modes test program
; compiled with MASM 5.10 assembler (before 4.20 ver - MASM6.00)

;0.96 patch for JUKO EGA card. The BIOS of this cards
	; destroy AX after call int10,2 (cursor positioning)
;1.00 first try for direct 6845 controlling
;1.05 first implementation direct 6845 controlling mode 4 and 5
;1.15 first implementation direct 6845 controlling mode 6
;1.20 add switching foreground colors into mode 6
;1.30 try to add composite test for NTSC out
;1.31 first more or less working variant for NTSC out
;1.32 add additiobal colors for NTSC out
;1.35 add additional test mode 4 for NTSC out
;2.00 new conception for NTSC test screen writing
;2.05 new procedure for NTSC write screen , mode 6
;2.10 new procedure for NTSC write screen , mode 5
;2.11 new help text
;2.30 first try for new code of write screen (int 10h)
;2.40 a lot of bag fix
;2.50 bag fix
;2.60 write NTSC composite screen function code optimisation
;2.70 new sequense in NTSC test, combined int10h and direct I/O in mode4/5 test
;2.71 combined int10h and direct I/O in mode6 test
;2.75 new help tekst
;2.80 new text strings for mode 6
;2.85 new help text, bug fix
;2.86 first try to add 160 x 100 mode
;2.87 delete foreground color swithing in mode6 due the in10h
;			foreground color set bug
;2.88 try to workaround foreground/background colors assign,
;	 but fail, it is unreliably
;2.89 optimising graphic's procedures
;2.90 code optimising, help text correctons
;2.92 lines quantity in the mode6 test were increased to 10
;2.94 text strings in mode 4 were added
;2.95 text strings in mode 4 were added
;3.00 unused code was deleted, bug fix in the color text rows show code
;3.10 correct the color text rows show code, hide cursor in mode 1,2,3,4
;3.15 try 2 make the 160x100 mode working
;3.20 try 3 make the 160x100 mode working
;3.25 try 4 make the 160x100 mode working
;3.30 update help text and fix serious bug with DS segment assign in 160x100 code
;3.35 minor changes
;3.40 cursor was hidden in text modes
;3.50 fix sync problem with G3101; add experimental mode 7, minor changes
;3.60 fix bug with JUKO EGA cards
;3.70 experimental mode 7 was deleted while
;3.80 addreses of 6845 regs have been obtained from BDA
;3.90 first try to switch 640x200 composite NTSC out to direct mode switch
;3.95 sync writing color/mode CGA regs to BDA in direct I/O modes
;4.00 add black color as background to tests 4 and 5
;4.01 minor changes, new help string
;4.05 corrections in the mode 1,2,3 and 4 routine
;4.10 sync writing color/mode CGA regs in the NTSC mode 6 test was deleted
;4.20 fix bug in cmdloop, compatibility with MASM 5.1 compiler
;4.30 first try to add MDA test
;4.40 second try to add MDA test
;4.50 first work implementation of MDA test
;4.60 subroutines have been moved to subr.asm
;4.70 a lot code optimization
;4.80 fix bugs in cmd parcer
;4.90 first try to add simple benchmark to NTSC test	
;5.00 second try to add benchmark, max val in ms = 655359ms, ~10.9 min
;5.10 minor correction bencmark code
;5.20 enable color on NTSC out during TV test mode6
;5.30 new text strings about modes in the NTSC out test
;5.40 first try to add Hercules test
;5.50 second try of HGC test. MDA and HGC tests were moved to mdahgc.asm file.
;		 All tests currently declared as subroutunes
;5.51 fix new bug in cmd parser, delete unused declarations
;5.55 third try of HGC test
;5.60 forth  try of HGC test, minor bugs have been fixed
;5.70 more or less normal variant of HGC test
;5.80 HGC test optimisation, bugs fix, minor changes
;5.90 add MDA/HGC card detection
;5.95 bug fix, minor changes
;6.00 hard 6845 port set for 160x100 CGA test,
;	more optimal proc for 160x100 mode, minor changes
;6.05 minor changes, more detailed commments
;6.10 first variant with one image segment and load test's images from files
;6.20 switching to initial video mode has been moved
;	 to every test procedure, minor changes
;6.30 first version with dynamic memory allocation for image buffer
;6.40 bug fix, minor changes
;6.50 first try to add cards switching,
;        add protection for running in the DOS 1.X
;6.55 new keys for cards switching and code optimizing
;6.60 update help topic, first try to add switching to EGA card
;6.70 macros for loading file to memory, a lot of bug fix
;6.80 Video HW test was added
;6.90 add EGA RAM size detection, fixed bug in HW test
;7.00 modify help text, new mode set cmd
;7.00LF new load_file subroutine instead macros, bug fix
;7.05LF new wait_key code, first implementation for moving image in H test
;7.10LF addings limits for vertical moving image in H test
;7.15LF	first variant with load image from file name that was written in CMD
;7.20LF second variant with load image from file, bugs fix
;7.25LF first variant with horizontal moving image in H test
;7.30LF	serious bugs were fixed
;7.35LF minor changes
;7.40LF new code for realloc mem, fixed serious bug with release mem
;7.50R  switching (conditional compiling) between strategies of reallocation
        ; memory in code and during linking (link /CP:1), minor changes
;7.55R new text strings in mode5 test, green/HI foreground screens have been
        ; added to mode6 test, help text has been added



PUBLIC indx_6845, set_video_mode, init_video_mode, file_handle
PUBLIC err_open_file_str, err_read_file_str
PUBLIC mem_alloc_err_str, mem_free_err_str, mem_block_addr, allocpara 

EXTRN   mode7:near, hgc_out:near, load_file:near
EXTRN	wait_key:near, print_str:near, set_cursor:near
EXTRN	write_mode4:near, write_6845:near, sync_fix:near
EXTRN   findmono:near, find6845:near
EXTRN   show_dx_ax:near

CGA_COLOR0	EQU	00h
CGA_COLOR1	EQU	01h
CGA_COLOR2	EQU	02h
CGA_COLOR3	EQU	03h

CGA_BLACK	EQU	00h
CGA_WHITE	EQU	01h
CGA_VBUF_SEG    EQU     0B800h

EGA	EQU	01h
CGA	EQU	02h
MONO	EQU	03h

;MODE_6845_BDA	EQU	65h ; addr of value in the 6845 mode control reg in BDA
COLOR_6845_BDA	EQU	66h ; addr of value in the 6845 color select reg in BDA

MEM_REALLOC     EQU     0
;------------------------------------------------------------------------
stack   segment para stack 'STACK'
        db 200h dup ('?')
stack  ends

;------------------------------------------------------------------------
data	segment para public 'DATA'
init_video_mode	db	00h
set_video_mode	db	00h

cursor_posi	dw	0000h
cursor_pos0	dw	0200h	; for "background color" string
cursor_pos1	dw	0800h	; for color 1 string
cursor_pos2	dw	0E00h	; for color 2 string
cursor_pos3	dw	1400h	; for color 3 string

sym_row		dw	40	; number of symbols per row (text modes)
indx_6845       dw      03D4h	; addr of 6845 index reg
mode_6845	dw      03D8h	; addr of 6845 mode control reg
color_6845	dw	03D9h	; addr of 6845 color select reg
status_6845	dw	03DAh	; addr of 6845 status reg

usage_str db " CGA/MDA/HGC card modes test v7.55R, (c) 2023 Emil Mammadov", 0Dh, 0Ah
        db "    usage: CT [mode|C|L|H|SM|SC(mode)|SE(mode)|T]", 0Dh, 0Ah
        db "    mode - CGA/MDA BIOS video mode (0-7)", 0Dh, 0Ah
        db " C - composite NTSC out test, mode switching sequence:", 0Dh, 0Ah
        db "    mode4 palette 0; mode4 palette 0 HI;", 0Dh, 0Ah
        db "    mode4 palette 1; mode4 palette 1 HI;", 0Dh, 0Ah
        db "    mode6 foreground white; mode6 foreground white HI", 0Dh, 0Ah
        db " MODE4/5 tests, color switching sequence:", 0Dh, 0Ah
        db "    background black/palette 0; background blue/palette 0;", 0Dh, 0Ah
        db "    background blue HI/palette 0; background blue HI/palette 0 HI;", 0Dh, 0Ah
        db "    background black/palette 1; background blue/palette 1;", 0Dh, 0Ah
        db "    background blue HI/palette 1; background blue HI/palette 1 HI;", 0Dh, 0Ah
        db "    then same, but with direct write instead int10h routine", 0Dh, 0Ah
        db " MODE6 test, color switching sequence:", 0Dh, 0Ah
        db "    foreground white; foreground green; foreground green HI", 0Dh, 0Ah
        db "    then same, but with direct write instead int10h routine", 0Dh, 0Ah
        db " L - non-standard CGA color 160 x 100 mode test", 0Dh, 0Ah
        db " H [filename]- hercules card test", 0Dh, 0Ah
        db "    moving image - Arrow U/D; Arrow L/R; Page U/D; Home/End", 0Dh, 0Ah
	db " SM  - switch to MDA/HGC card", 0Dh, 0Ah
        db " SCmode - switch to CGA card; mode (0 - 3)", 0Dh, 0Ah
        db " SEmode - switch to EGA card; mode (0 - 3)", 0Dh, 0Ah
        db " T - test video hardware", 0Dh, 0Ah, '$'

error_dosver_str	db " DOS version must be 2.00 or above!", 0Dh, 0Ah, '$'
ovl_str			db "Overflow!", 0
ms_str			db " ms",0

mode4_pal0_s		db "CGA mode 4, Palette 0   ", 0
mode4_pal0h_s		db "CGA mode 4, Palette 0 HI", 0
mode4_pal1_s    	db "CGA mode 4, Palette 1   ", 0
mode4_pal1h_s   	db "CGA mode 4, Palette 1 HI", 0

mode5_pal0_s    	db "CGA mode 5, Palette 0   ", 0
mode5_pal0h_s   	db "CGA mode 5, Palette 0 HI", 0
mode5_pal1_s    	db "CGA mode 5, Palette 1   ", 0
mode5_pal1h_s   	db "CGA mode 5, Palette 1 HI", 0

mode4_pal0_dw_s		db "CGA mode 4, Palette 0     Direct write", 0
mode4_pal0h_dw_s	db "CGA mode 4, Palette 0 HI  Direct write", 0
mode4_pal1_dw_s		db "CGA mode 4, Palette 1     Direct write", 0
mode4_pal1h_dw_s	db "CGA mode 4, Palette 1 HI  Direct write", 0

mode5_pal0_dw_s		db "CGA mode 5, Palette 0     Direct write", 0
mode5_pal0h_dw_s	db "CGA mode 5, Palette 0 HI  Direct write", 0
mode5_pal1_dw_s		db "CGA mode 5, Palette 1     Direct write", 0
mode5_pal1h_dw_s	db "CGA mode 5, Palette 1 HI  Direct write", 0

ntsc_m4_p0_s		db "NTSC mode 4, Palette 0   ", 0 
ntsc_m4_p0h_s		db "NTSC mode 4, Palette 0 HI", 0 
ntsc_m4_p1_s		db "NTSC mode 4, Palette 1   ", 0 
ntsc_m4_p1h_s		db "NTSC mode 4, Palette 1 HI", 0 
ntsc_m6_s		db "NTSC mode 6              ", 0 
ntsc_m6h_s		db "NTSC mode 6 HI           ", 0 

back_black_str		db "Background Color Black  ", 0
back_blue_str		db "Background Color Blue   ", 0
back_blueh_str		db "Background Color Blue HI", 0

pal0_c1_str     db "Green     ", 0
pal0_c2_str     db "Red       ", 0
pal0_c3_str     db "Brown     ", 0
pal0h_c1_str    db "Green   HI", 0
pal0h_c2_str    db "Red     HI", 0
pal0h_c3_str    db "Yellow    ", 0

pal1_c1_str     db "Cyan      ", 0
pal1_c2_str     db "Magenta   ", 0
pal1_c3_str     db "Gray      ", 0
pal1h_c1_str    db "Cyan    HI", 0
pal1h_c2_str    db "Magenta HI", 0
pal1h_c3_str    db "White     ", 0

if 0
color1_str	db "Color 1   ", 0
color2_str	db "Color 2   ", 0
color3_str	db "Color 3   ", 0
color1h_str	db "Color 1 HI", 0
color2h_str	db "Color 2 HI", 0
color3h_str	db "Color 3 HI", 0
else
color1_str	db "Cyan      ", 0
color2_str	db "Red       ", 0
color3_str	db "Grey      ", 0
color1h_str	db "Cyan    HI", 0
color2h_str	db "Red     HI", 0
color3h_str	db "White     ", 0
endif

mode6_s			db "CGA mode 6 B/W                       ", 0
mode6_green_s		db "CGA mode 6, Foreground Color Green   ", 0
mode6_green_hi_s	db "CGA mode 6, Foreground Color Green HI", 0
mode6_dw_s              db "CGA mode 6 B/W                         Direct write", 0
mode6_green_dw_s        db "CGA mode 6, Foreground Color Green     Direct write", 0
mode6_green_dw_hi_s     db "CGA mode 6, Foreground Color Green HI  Direct write", 0

; Color strings for text modes
black_str	db "Black      ", 0Dh, 0Ah, 0
blue_str	db "Blue       ", 0Dh, 0Ah, 0
green_str	db "Green      ", 0Dh, 0Ah, 0
cyan_str	db "Cyan       ", 0Dh, 0Ah, 0
red_str		db "Red        ", 0Dh, 0Ah, 0
magenta_str	db "Magenta    ", 0Dh, 0Ah, 0
brown_str	db "Brown      ", 0Dh, 0Ah, 0
gray_str	db "Gray       ", 0Dh, 0Ah, 0

hi_black_str	db "HI Black   ", 0Dh, 0Ah, 0
hi_blue_str	db "HI Blue    ", 0Dh, 0Ah, 0
hi_green_str	db "HI Green   ", 0Dh, 0Ah, 0
hi_cyan_str	db "HI Cyan    ", 0Dh, 0Ah, 0
hi_red_str	db "HI Red     ", 0Dh, 0Ah, 0
hi_magenta_str	db "HI Magenta ", 0Dh, 0Ah, 0
yellow_str	db "Yellow     ", 0Dh, 0Ah, 0
white_str	db "White      ", 0Dh, 0Ah, 0

; CGA 160x100 mode params
C160X100_param  db      00,  113  ; horizontal total
                db      01,  80   ; horizontal displayed
                db      02,  90   ; horizontal sync pos
                db      03,  10   ; horizontal sync with
                db      04, 127   ; vertical total *127 max, else no hor sync
                db      05,  06   ; vertical total adjust 06
                db      06, 100   ; vertical displayed 25 100
                db      07, 112   ; vertical sync pos 28  135
                db      08,  02   ; interlace mode
                db      09,  01   ; max scan line 07
                db      0Ah, 00100110b  ; cursor start 06 and hide cursor (bit5)
                db      0Bh, 07   ; cursor ebd
                db      0Ch, 00   ; start addr H 
                db      0Dh,  00   ; start addr L
C160X100_len    EQU ($ - C160X100_param)/2

file_handle	dw	0000h
ntscdata_file_s	db	"NTSCDATA.IMG", 0
c160100d_file_s	db	"C160100D.IMG", 0
h_bmp_file_s	db      "800600BW.BMP", 0

err_open_file_str       db      " file open error!", 0Dh, 0Ah, 0
err_read_file_str       db      " file read error!", 0Dh, 0Ah, 0

allocpara               dw      0000h
mem_block_addr          dw      0000h   ; addr of mem block address in para
mem_alloc_err_str       db      "Memory allocation error!", 0Dh, 0Ah, 0
mem_free_err_str        db      "Memory freeing error!", 0Dh, 0Ah, 0
if MEM_REALLOC
mem_realloc_err_str	db	"Memory reallocation error!", 0Dh, 0Ah, 0
endif

act_card	db	00h
no_mono_str	db	"MDA adapter was not found!", 0Dh, 0Ah, 0
no_cga_str	db	"CGA adapter was not found!", 0Dh, 0Ah, 0
no_ega_str	db	"EGA adapter was not found!", 0Dh, 0Ah, 0

none_str	db	"NONE", 0Dh, 0Ah, 0
ok_str		db	"OK", 0Dh, 0Ah, 0

mono_str	db     "MONO", 0Dh, 0Ah, 0  
mda_str		db	"MDA", 0Dh, 0Ah, 0  
hgc_str		db	"HGC", 0Dh, 0Ah, 0  
ega_str		db	"EGA", 0Dh, 0Ah, 0  
cga_str		db	"CGA", 0Dh, 0Ah, 0  
cga40_str	db	"CGA 40x25", 0Dh, 0Ah, 0  
cga80_str	db	"CGA 80x25", 0Dh, 0Ah, 0  

detect_cga_str	db	" Detect CGA 6845 card...", 0
detect_ega_str	db	" Detect EGA card........", 0
detect_mono_str	db	" Detect MONO card.......", 0
active_card_str	db	" Active card............", 0


m64k_str	db	"OK, 064 KB RAM", 0Dh, 0Ah, 0
m128k_str	db	"OK, 128 KB RAM", 0Dh, 0Ah, 0
m192k_str	db	"OK, 192 KB RAM", 0Dh, 0Ah, 0
m256k_str	db	"OK, 256 KB RAM", 0Dh, 0Ah, 0
data	ends

;---------------------------------------------------------------------------
code	segment	byte public 'CODE'
if MEM_REALLOC
assume cs:code, ds:data, es:zseg, ss:stack
else
assume cs:code, ds:data, es:nothing, ss:stack
endif

main    proc    far
;---------------------------------------------------------------------------
; in this section, for checking DOS version we use old stile
; functions, for compatibility with DOS 1.X
	mov	ah, 30h		; get DOS version in AL
	int	21h
	cmp	al, 02
	jae @F			; if DOS version above or equal 2.00, work
	push	ds		; move to stack the para of PSP
	mov	ax, 0		; for return to DOS by RETF
	push	ax		; move to stack zero offset of address
	mov	ax, data	; init ds, for print string function
	mov	ds, ax
	mov	dx, offset error_dosver_str
	mov	ah, 09h		; print error string
	int	21h
	retf			; old style return to DOS

;---------------------------------------------------------------------------
@@:
	mov	ax, data
	mov	ds, ax

if MEM_REALLOC 
; release unused memory
        mov     bx, SEG zseg	; get number ending para of program + 1
	mov	ax, es		; get number  begining para of program
	sub	bx, ax		; calc size of program in para
	mov	ah, 4Ah		; realloc memory
	int	21h
        jnc     @F
	mov     si, offset mem_realloc_err_str
	call    print_str
	jmp	exit
@@:
endif

; get initial video mode
	mov	ah, 0Fh
	int	10h
    	mov	init_video_mode, al	; save current video mode

	push	es
; get base port address for active 6845 CRT controller
	mov	ax, 0040h
	mov	es, ax
	mov	ax, word ptr es:[63h]
	mov	indx_6845, ax

	add	ax, 4
	mov	mode_6845, ax	; addr of 6845 mode control reg

	inc	ax
	mov	color_6845, ax	; addr of 6845 color select reg

	inc	ax
	mov	status_6845, ax	; addr of 6845 status reg
	pop	es

;****************** get command line argument ********************************
	mov	al, byte ptr es:[80h]
	or	al, al		; if length of string is equal zero,
				; show usage and exit
	jnz	@F
	jmp	show_usage
@@:
	mov	cl, al		; mov length of string to cx
	mov	ch, 00h

	mov	si, 81h		; get addr of first letter to cx
	cld
cmdloop:
	lods	byte ptr es:[si]
	cmp	al, ' '		; if space or TAB (09h), loop
	je	@F
	cmp	al, 09h		; 09h - TAB code
@@:
	loope	cmdloop

	cmp	al, 0Dh		; if 0Dh exit
	jne	@F
	jmp	show_usage
@@:
	cmp	al, 0		; if 0 exit
	jne	@F
	jmp	show_usage
@@:
	or	al, 20h		; convert symbol to lower case

	cmp	al, '0'
	jne	@F
	and	al, 0Fh		; get mode number (0-F) in AL
	call	mode0123
        jmp     exit
@@:
	cmp	al, '1'
	jne	@F
	and	al, 0Fh		; get mode number (0-F) in AL
	call	mode0123
        jmp     exit
@@:
	cmp	al, '2'
	jne	@F
	and	al, 0Fh		; get mode number (0-F) in AL
	call	mode0123
        jmp     exit
@@:
	cmp	al, '3'
	jne	@F
	and	al, 0Fh		; get mode number (0-F) in AL
	call	mode0123
        jmp     exit
@@:
	cmp	al, '4'
	jne	@F
	and	al, 0Fh		; get mode number (0-F) in AL
	call	mode45
        jmp     exit
@@:
	cmp	al, '5'
	jne	@F
	and	al, 0Fh		; get mode number (0-F) in AL
	call	mode45
        jmp     exit
@@:
	cmp	al, '6'
	jne	@F
	and	al, 0Fh		; get mode number (0-F) in AL
	call	mode6
        jmp     exit
@@:
	cmp	al, '7'
	jne	@F
	and	al, 0Fh		; get mode number (0-F) in AL
	call	mode7
        jmp     exit
@@:
	cmp	al, 'c'
        jne	@F
        lea     dx, ntscdata_file_s
        call    ntsc_out         ; composite NTSC out test
        jmp     exit
@@:
	cmp	al, 'l'
	jne	@F
        lea     dx, c160100d_file_s
        call    c160_100         ; 160 x 100 color mode test
        jmp     exit
@@:
	cmp	al, 'h'
	jne	@F
        call    get_cmd_fname   ; get file name from cmd str to h_bmp_file_s
        lea     dx, h_bmp_file_s
        call    hgc_out				; Hercules test
        jmp     exit
@@:
        cmp     al, 't'
	jne	@F
        call    vhw_detect         ; video hardware detection
        jmp     exit
@@:
	cmp	al, 's'
	jne	show_usage
; take next symbol
	lods	byte ptr es:[si]
	or	al, 20h		; convert new symbol to lower case
	cmp	al, 'm'
	jne	@F
        call    mda_sw         ; switch to MDA/HGC
        jmp     exit
@@:         
        cmp     al, 'e'
	jne	@F
        lods    byte ptr es:[si] ; load new symbol
        and     al, 0Fh          ; convert to digit
        cmp     al, 3          ; check new symbol, if 0-1, set 40x25, 2-3 80x25
        ja      show_usage
        call    ega_sw          ; switch to EGA mode1-3
	jmp	exit

@@:
	cmp	al, 'c'
	jne	show_usage
	lods	byte ptr es:[si] ; load new symbol
        and     al, 0Fh          ; convert to digit
        cmp     al, 3          ; check new symbol, if 0-1, set 40x25, 2-3 80x25
        ja      show_usage
        call    cga_sw          ; switch to CGA mode1-3
	jmp	exit

; if valid modes were not found, then to print usage and exit
show_usage:
	mov	ah, 09h		; show message "usage"
	mov	dx, offset usage_str
	int	21h
	jmp	exit

;***************************Video cards detection***************************
vhw_detect proc near
;--------------------detect CGA 6845 compatible card------------------------
        mov     si, offset detect_cga_str
        call    print_str
        mov     dx, 3D4h        ; DX address of video controller port
	call	find6845
        mov     si, offset none_str
        jc     @F
        mov     si, offset ok_str
@@:
        call    print_str

;--------------------------detect EGA card------------------------------
        mov     si, offset detect_ega_str
        call    print_str
	mov	ax, 40h
	mov	es, ax
	mov	al, es:[87h]
        mov     si, offset none_str
	cmp	al, 0
        jz      ega_det_end
	test	al, 00001000b	; if EGA present, by inactive, bit3-> 1
	jnz	@F
	mov	act_card, EGA	; if bit3->0, EGA active
@@:
; detect EGA RAM size and print that EGA found
	mov	ah, 12h
        mov     bl, 10h
	int	10h
	and	bl, 03h
        mov     si, offset m64k_str
	cmp	bl, 00h	
	je	@F	
        mov     si, offset m128k_str
	cmp	bl, 01h	
	je	@F	
        mov     si, offset m192k_str
	cmp	bl, 02h	
	je	@F	
        mov     si, offset m256k_str
@@:
ega_det_end:
        call    print_str

;--------------------------detect MDA/HGC card------------------------------
        mov     si, offset detect_mono_str
        call    print_str
 	call	findmono	; (CF == 1) -> no HGC, no MDA
        mov     si, offset none_str
	jc	@F
        mov     si, offset mda_str
	cmp	al, 01h		; ((AL == 01h) && (CF==0)) -> MDA found
        je     @F
        mov     si, offset hgc_str
@@:
        call    print_str

;--------------------------detect active card------------------------------
        mov     si, offset active_card_str
        call    print_str
        mov     si, offset none_str
        cmp     act_card, EGA   ; if EGA active (earlier it was detected),
        jne     @F              ; print message and retn
        mov     si, offset ega_str
	call	print_str
	retn

@@:
	mov	al, es:[10h]
	and	al, 00110000b	; if MONO card present, bits 4 and 5 are 11
	cmp	al, 00110000b
	jne	@F
        mov     si, offset mono_str
	call    print_str
	retn

@@:	; CGA check
	mov	al, es:[10h]
	and	al, 00010000b	; if CGA 40x25 present, bit4->1, bit5->0
	cmp	al, 00010000b
	jne	@F
	mov     si, offset cga40_str
	call	print_str
	retn

@@:
	mov	al, es:[10h]
	and	al, 00100000b	; if CGA 80x25 present, bit4->0, bit5->1
	cmp	al, 00100000b
	jne	@F
	mov     si, offset cga80_str
	call	print_str
	retn
@@:
	call	print_str
	retn

vhw_detect endp

;*********************Video cards switching subroutines*********************
mda_sw proc near
	call	findmono	; (CF == 1) -> no HGC, no MDA
	jnc	@F
        mov     si, offset no_mono_str
        call    print_str
        retn

@@:
        mov     bx, 40h
        mov     es, bx	; set EX to BDA
	or	byte ptr es:[10h], 00110000b	; set bit 5 and 4

        mov     ax, 0007h
        int     10h		; set mode 7
        retn
mda_sw endp

;----------------------------------------------------------------------------
cga_sw proc near
; new screen mode in AL, 0-1 for 40x25, 2-3 for 80x25
        mov     dx, 3D4h        ; DX address of video controller port
        push    ax              ; save AL
	call	find6845
        pop     ax              ; restore AL
	jnc	@F
        mov     si, offset no_cga_str
        call    print_str
        retn

@@:
        mov     bx, 40h
        mov     es, bx  ; set BX to BDA
        and	byte ptr es:[10h], 11001111b	; reset bit 4 and 5
        cmp     al, 01h  
        ja      @F
	or	byte ptr es:[10h], 00010000b	; set bit 4 (40x25)
	jmp	short set_cga_modesw
@@:
	or	byte ptr es:[10h], 00100000b	; set bit 5 (80x25)
  
set_cga_modesw:
        mov     ah, 00h                ; set mode, in AL->mode
        int     10h
        retn
cga_sw endp

;-------------------------------------------------------------------------
ega_sw proc near
; new screen mode in AL, 0-1 for 40x25, 2-3 for 80x25
        mov     bx, 40h
        mov     es, bx          ; set ES to BDA
        cmp     byte ptr es:[87h], 00h  ; if zero, no EGA
	jne	@F
        mov     si, offset no_ega_str
        call    print_str
        retn

@@:
        and     byte ptr es:[10h], 11001111b    ; reset bit4 and 5 (EGA)
        mov     ah, 00h         ; set mode, in AL->mode
        int     10h
        retn
ega_sw endp

;********************NTSC Composite Out Color test*****************************
ntsc_out proc near
; load file into mem
        mov     allocpara, 1000
        call    load_file
        jnc     @F      ; exit, if CF was set
        retn
@@:

; CGA mode 4 for NTSC out
	mov	ah, 00h		; set mode function
	mov	al, 04h		; set CGA mode 04
	int	10h
; bit0 set blue  color
; bit1 set green color
; bit2 set red   color
; bit3 set intensity for background's colors
; bit4 set intensity for pallette's colors
; bit5 - palette
; bit6 - not used
; bit7 - not used

; set black as background color, palette 0
        mov     bh, 00h
        mov     bl, 00000000b	; set black background color
	mov	ah, 0Bh
        int     10h

; set palette
	mov	bh, 01h
	mov	bl, 00h		; set palette 00h
	mov	ah, 0Bh
	int	10h

;  prepare initial counter value for bencmark
        mov     ax, 40h
        mov     es, ax
        mov     ax, word ptr es:[6Ch]
        push    ax  ; save value in stack

; write all graphic screen
; SI - screen data offset
; ES - segment addr of screen data
        push    es
        mov     ax, mem_block_addr
        mov     es, ax
        mov     si, 0000h       ; offset of image data
        call write_mode4
        pop     es

; calculating and show bencmark value, ES = 40h
        mov     ax, word ptr es:[6Ch]   ; get ending counter value
        mov     dx, 0000h       ; cursor to row 0 : col 0
	call	set_cursor

        pop     bx       ; restore initial counter value from stack to bx
        sub     ax, bx   ; calculate time in ~55ms quants
        mov     bx, 55   ; mul time to ~55ms for getting time in ms in DX:AX
        mul     bx

        mov     si, offset ovl_str      ; prepare "overflow!" str

if 0    ; only for test purpose
        mov     ax, 65535
        mov     dx, 10
endif
    
	cmp     dx, 10          ; if DX above or equal 10, show Ovl str
        jae     @F              ; jump for preventing divide overflow int
        call    show_dx_ax ; show value from DX:AX after mul
        mov     si, offset ms_str
@@:
	call	print_str

        mov     dx, 000Fh       ; cursor to row 0 : col 15
	call	set_cursor
        mov     si, offset ntsc_m4_p0_s
	call	print_str
	call	wait_key


; bit0 set blue  color
; bit1 set green color
; bit2 set red   color
; bit3 set intensity for background's colors
; bit4 set intensity for pallette's colors
; bit5 - set palette
; bit6 - not used
; bit7 - not used
        mov     bh, 00h
        mov     bl,  00010000b          ; set intensified color
	mov	ah, 0Bh
        int     10h

        mov     dx, 000Fh       ; cursor to row 0 : col 15
	call	set_cursor
        mov     si, offset ntsc_m4_p0h_s
	call	print_str
	call	wait_key


        mov     bh, 00h
        mov     bl, 00000000b		; set normal color
	mov	ah, 0Bh
        int     10h

        mov     bh, 01h
        mov     bl,  000000001b          ; set palette 1
	mov	ah, 0Bh
        int     10h

        mov     dx, 000Fh       ; cursor to row 0 : col 15
	call	set_cursor
        mov     si, offset ntsc_m4_p1_s
	call	print_str
	call	wait_key


        mov     bh, 00h
        mov     bl, 00010000b          ; set intensified color
	mov	ah, 0Bh
        int     10h

        mov     dx, 000Fh       ; cursor to row 0 : col 15
	call	set_cursor
        mov     si, offset ntsc_m4_p1h_s
	call	print_str
	call	wait_key

;---------------------- NTSC out, CGA mode 6 -------------------------------
; mode control reg
; bit0   1 -> 80x25, 0 ->40x25, graphics modes ->0
; bit1   1-> 320x200 mode, 0 -> text mode
; bit2   1-> B/W mode on NTSC out, 0-> color mode on NTSC out 
; bit3   1-> enable video signal, 0-> disable
; bit4   1-> enable high res 640x200 mode
; bit5   1-> blinking function, 0-> high intensity
; 80x25  color off at NTSC out ????

	mov	dx, mode_6845
	mov	al, 00011010b		; 1Eh for BW mode on composite out
	out	dx, al			; 1Ah for color mode on composite out
					; bit2 0 -> color mode; 1-> B/W mode
					; bit2 doesn't affected for RGB out

	mov	dx, color_6845
        mov     al, 00000111b           ; normal intensity
	out	dx, al

        mov     dx, 000Fh       ; cursor to row 0 : col 15
	call	set_cursor
        mov     si, offset ntsc_m6_s
	call	print_str
	call	wait_key

	mov	dx, color_6845
        mov     al, 00001111b           ; high intensity
	out	dx, al

        mov     dx, 000Fh       ; cursor to row 0 : col 15
	call	set_cursor
        mov     si, offset ntsc_m6h_s
	call	print_str
	call	wait_key


        mov     ah, 00h
	mov	al, init_video_mode	; return old video mode
	int	10h
        call    sync_fix        ; ??? for G3101

        mov     ax, mem_block_addr
        mov     es, ax
        mov     ah, 49h
        int     21h
        jnc     @F
        mov     si, offset mem_free_err_str
        call    print_str
@@:
	retn
ntsc_out endp

;******************Non-standard 160 x 100 16 color mode*********************
c160_100 proc near
; CGA mode 3	(80 x 25, 16 color)
; since this mode is not supported by BIOS, we use direct operations
; and also use hard settings the addresses of 6845 I/O ports

; load file into mem
        mov     allocpara, 1000
        call    load_file
        jnc     @F      ; exit, if CF was set
        retn

@@:
        mov     dx, 3D9h        ; CGA color select reg
        mov     al, 00000000b
        out     dx, al

        mov     dx, 3D8h                ; mode control reg of 6845
        mov     al, 00000001b           ; disable video signal
	out	dx, al

; 6845 controller init
; AL - reg number (index)
; AH - value to vrite
; DX -> 6845 index port , 3D4h
        mov     dx, 3D4h        ; 6845 index port
        mov     si, offset C160X100_param
        mov     cx, C160X100_len
@@:
	lodsw
        call    write_6845
        loop    @B

        mov     dx, 3D8h        ; mode control reg of 6845
        mov     al, 00001001b	; enable video signal
	out	dx, al

        mov     ax, CGA_VBUF_SEG
	mov	es, ax
        mov     di, 0000h       ; zero offset in seg

        push    ds
        mov     ax, mem_block_addr
	mov	ds, ax
	cld
        mov     cx, 8000
        mov     si, 0000h       ; offset of image data
rep     movs    word ptr es:[di], word ptr ds:[si]
        pop     ds
	call	wait_key

        mov     ah, 00h
	mov	al, init_video_mode	; return old video mode
	int	10h
        call    sync_fix        ; ??? for G3101

	mov     ax, mem_block_addr
	mov     es, ax
        mov     ah, 49h
        int     21h
        jnc     @F
        mov     si, offset mem_free_err_str
        call    print_str
@@:
	retn
c160_100 endp

;******************Write screen for CGA modes 0, 1, 2, 3*******************
; mode in AL
mode0123 proc near
	mov	ah, 00h		; set mode function
	push	ax
	mov	set_video_mode, al
	int	10h
	pop	ax

	cmp	al, 2
	jb	@F
	mov	sym_row, 80
@@:

; show all symbols from ROM
; write symbols to screen by BIOS functions

	mov	dh, 02		; cursor row
	mov	dl, 02		; cursor column
	call	set_cursor	; set cursor for symbol table
	mov	al, 00h		; starting symbol
        mov     bh, 00h         ; page 0
        mov     bl, 07h         ; attribute

write_rows:
	mov	cx, 16
@@:
	push	dx
	push	ax
	mov	ah, 09h
	int	10h	; - VIDEO - WRITE CHARACTER AND	ADVANCE	CURSOR (TTY WRITE)
			; AL = character, BH = display page
			; BL = foreground color	(graphics modes)
	pop	ax
	pop	dx

	inc	al
	inc	dl
	call	set_cursor	; set cursor for symbol table
	loop	@B

	inc	dh
	mov	dl, 02
	call	set_cursor	; set cursor for symbol table
	cmp	dh, (16+2)
	jb	write_rows

; hide cursor
	mov	dh, 25		; cursor row
	mov	dl, 00		; cursor column
	call	set_cursor

	call	wait_key

;---------------- show all colors for CGA mode 0, 1, 2 and 3 -----------------
; set mode for clear screen
	mov	ah, 00h
	mov	al, set_video_mode
	int	10h

	mov	dh, 04		; cursor row
	mov	dl, 00h		; cursor column
	mov	bl, 00h		; attribute
	mov	cx, 16

color_txt_loop:
	push	cx
	push	dx
	push	bx

	call	set_cursor
	mov	cx, sym_row	; 80 for mode 2,3 and 40 for mode 0,1 (repeat)
        mov     bh, 00h         ; page 0
	mov	al, 219

; correction for doing "black" string visible
	cmp	bl, 00h
	jne	@F
	mov	bl, 07h	; att is white for symbol, black for background
	mov	al, 00h	; symbol "empty", print as black
@@:
; correction for doing "HI black" string visible
	cmp	bl, 08h
	jne	@F
	mov	bl, 78h	; att is HI black for symbol, white for background
	mov	al, 219	; symbol is "full rectangle", print as black HI
@@:
	mov	ah, 09h		; write str with attributes
	int	10h

	pop	bx
	pop	dx
	pop	cx

	inc	dh		; inc row number
	inc	bl		; inc color code
	loop	color_txt_loop


	mov	dh, 04h		; cursor row
	mov	dl, 00h		; cursor column
	call	set_cursor

	mov	si, offset black_str
	call	print_str
	mov	si, offset blue_str
	call	print_str
	mov	si, offset green_str
	call	print_str
	mov	si, offset cyan_str
	call	print_str
	mov	si, offset red_str
	call	print_str
	mov	si, offset magenta_str
	call	print_str
	mov	si, offset brown_str
	call	print_str
	mov	si, offset gray_str
	call	print_str

	mov	si, offset hi_black_str
	call	print_str
	mov	si, offset hi_blue_str
	call	print_str
	mov	si, offset hi_green_str
	call	print_str
	mov	si, offset hi_cyan_str
	call	print_str
	mov	si, offset hi_red_str
	call	print_str
	mov	si, offset hi_magenta_str
	call	print_str
	mov	si, offset yellow_str
	call	print_str
	mov	si, offset white_str
	call	print_str

; hide cursor
	mov	dh, 25		; cursor row
	mov	dl, 00		; cursor column
	call	set_cursor
	call	wait_key

        mov     ah, 00h
	mov	al, init_video_mode	; return old video mode
	int	10h

	retn
mode0123 endp

;******************Write screen for CGA mode 04 and 05***************************
; mode in AL
mode45 proc near
	mov	ah, 00h			; set mode function
	mov	set_video_mode, al
	int	10h

        mov     bh, 00h
	mov	bl, 000000000b		; set black as background color
	mov	ah, 0Bh
        int     10h

; set palette
	mov	bh, 01h
	mov	bl, 00h			; set palette 00h
	mov	ah, 0Bh
	int	10h

	mov	ah, 0Ch		; write point function
	mov	al, CGA_COLOR1
	mov	cx, 00h		; column
	mov	dx, 50		; first row with non-background color

color45_loop:
 	push	ax
	int	10h
	pop	ax
	inc	cx
        cmp     cx, 320
	jne	color45_loop
	mov	cx, 00h
	inc	dx

	cmp	dx, 100
	jne	@F
	mov	al, CGA_COLOR2
@@:

	cmp	dx, 150
	jne	@F
	mov	al, CGA_COLOR3
@@:
	cmp     dx, 200
	jne	color45_loop

        mov     dx, cursor_posi
	call	set_cursor
	mov	si, offset mode4_pal0_s
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset mode5_pal0_s
@@:
	call    print_str

	mov	dx, cursor_pos0
	call	set_cursor
	mov	si, offset back_black_str
	call	print_str

	mov	dx, cursor_pos1
	call	set_cursor
	mov	si, offset pal0_c1_str
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset color1_str
@@:
	call	print_str

	mov	dx, cursor_pos2
	call	set_cursor
	mov	si, offset pal0_c2_str
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset color2_str
@@:
	call	print_str

	mov	dx, cursor_pos3
	call	set_cursor
	mov	si, offset pal0_c3_str
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset color3_str
@@:
	call	print_str
	call	wait_key


	mov	bh, 00h
	mov	bl, 000000001b		; set blue as background color
	mov	ah, 0Bh
	int	10h

	mov	dx, cursor_pos0
	call	set_cursor
	mov	si, offset back_blue_str
	call	print_str
	call	wait_key


	mov	bh, 00h
	mov	bl, 000001001b		; set blue as HI background color
	mov	ah, 0Bh
	int	10h

	mov	dx, cursor_pos0
	call	set_cursor
	mov	si, offset back_blueh_str
	call	print_str
	call	wait_key


	mov	bh, 00h
	mov	bl, 000011001b		; set blue as HI background color
					; and HI palette's colors
	mov	ah, 0Bh
	int	10h

        mov     dx, cursor_posi
	call	set_cursor
        mov     si, offset mode4_pal0h_s
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset mode5_pal0h_s
@@:
	call	print_str

	mov	dx, cursor_pos1
	call	set_cursor
	mov	si, offset pal0h_c1_str
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset color1h_str
@@:
	call	print_str

	mov	dx, cursor_pos2
	call	set_cursor
	mov	si, offset pal0h_c2_str
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset color2h_str
@@:
	call	print_str

	mov	dx, cursor_pos3
	call	set_cursor
	mov	si, offset pal0h_c3_str
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset color3h_str
@@:
	call	print_str
	call	wait_key


	mov	bh, 01h
	mov	bl, 01h		; set palette 01h
	mov	ah, 0Bh
	int	10h

	mov	bh, 00h
	mov	bl, 000000000b		; set black as background color
	mov	ah, 0Bh
	int	10h

	mov	dx, cursor_posi
	call	set_cursor
        mov     si, offset mode4_pal1_s
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset mode5_pal1_s
@@:
	call	print_str

        mov     dx, cursor_pos0
	call	set_cursor
        mov     si, offset back_black_str
	call	print_str

	mov	dx, cursor_pos1
	call	set_cursor
        mov     si, offset pal1_c1_str
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset color1_str
@@:
	call	print_str

	mov	dx, cursor_pos2
	call	set_cursor
	mov	si, offset pal1_c2_str
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset color2_str
@@:
	call	print_str

	mov	dx, cursor_pos3
	call	set_cursor
	mov	si, offset pal1_c3_str
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset color3_str
@@:
	call	print_str
	call	wait_key


	mov	bh, 00h
	mov	bl, 000000001b		; set blue as background color
	mov	ah, 0Bh
	int	10h

        mov     dx, cursor_pos0
	call	set_cursor
        mov     si, offset back_blue_str
	call	print_str
        call    wait_key

	mov	bh, 00h
	mov	bl, 000001001b		; set blue as HI background color
	mov	ah, 0Bh
	int	10h

        mov     dx, cursor_pos0
	call	set_cursor
        mov     si, offset back_blueh_str
	call	print_str
        call    wait_key

	mov	bh, 00h
	mov	bl, 000011001b		; set blue as HI background color
					; and HI palette's colors
	mov	ah, 0Bh
	int	10h

        mov     dx, cursor_posi
	call	set_cursor
        mov     si, offset mode4_pal1h_s
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset mode5_pal1h_s
@@:
	call	print_str

	mov	dx, cursor_pos1
	call	set_cursor
        mov     si, offset pal1h_c1_str
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset color1h_str
@@:
	call	print_str

	mov	dx, cursor_pos2
	call	set_cursor
        mov     si, offset pal1h_c2_str
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset color2h_str
@@:
	call	print_str

	mov	dx, cursor_pos3
	call	set_cursor
        mov     si, offset pal1h_c3_str
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset color3h_str
@@:
	call	print_str
	call	wait_key

;--------------------same mode4/5 test, but with direct I/O--------------------
; set background color
; bit0 set blue  color
; bit1 set green color
; bit2 set red   color
; bit3 set intensity for background's colors
; bit4 set intensity for pallette's colors
; bit5 - set palette
; bit6 - not used
; bit7 - not used

; set black as background color and palette 0
	mov	ax, 0040h
	mov	es, ax			; ES > BDA segment
	mov	dx, color_6845		; 3d9h
	mov	al, 00000000b
	out	dx, al
	mov	byte ptr ES:[COLOR_6845_BDA], al

 ; write point
        mov     ax, CGA_VBUF_SEG
        mov     es, ax		; ES > video buf segment
        mov     al, 00000000b	; color 0
        mov     si, 00000h	; mem addr for even rows
	mov	di, 02000h	; mem addr for odd rows

color4d_loop:
        mov     byte ptr es:[si], al
	mov     byte ptr es:[di], al
        inc     si
	inc	di
        cmp     si, 2000          ; 100str/4 = 25
				  ; 25 * 320 /4 = 2000
	jne	@F
	mov	al, 01010101b	; color 1
@@:
        cmp     si, 4000
	jne	@F
	mov	al, 10101010b	; color 2
@@:
	cmp	si, 6000
	jne	@F
	mov	al, 11111111b	; color 3
@@:
	cmp	si, 8000
	jb	color4d_loop


; write strings
; since we set mode by int10h, we can write strings also by int10h
        mov     dx, cursor_posi
	call	set_cursor
	mov	si, offset mode4_pal0_dw_s
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset mode5_pal0_dw_s
@@:
        call    print_str

	mov	dx, cursor_pos0
	call	set_cursor
	mov	si, offset back_black_str
	call	print_str

	mov	dx, cursor_pos1
	call	set_cursor
	mov	si, offset pal0_c1_str
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset color1_str
@@:
	call	print_str

	mov	dx, cursor_pos2
	call	set_cursor
	mov	si, offset pal0_c2_str
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset color2_str
@@:
	call	print_str

	mov	dx, cursor_pos3
	call	set_cursor
	mov	si, offset pal0_c3_str
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset color3_str
@@:
	call	print_str
	call	wait_key


; set blue as background color and palette 0
	mov	ax, 0040h
	mov	es, ax			; ES > BDA segment
	mov	dx, color_6845		; 3d9h
	mov	al, 00000001b
	out	dx, al
	mov	byte ptr ES:[COLOR_6845_BDA], al

	mov	dx, cursor_pos0
	call	set_cursor
	mov	si, offset back_blue_str
	call	print_str
	call	wait_key


; set blue HI as background color and palette 0
	mov	ax, 0040h
	mov	es, ax			; ES > BDA segment
	mov	dx, color_6845		; 3d9h
	mov	al, 00001001b
	out	dx, al
	mov	byte ptr ES:[COLOR_6845_BDA], al

	mov	dx, cursor_pos0
	call	set_cursor
	mov	si, offset back_blueh_str
	call	print_str
	call	wait_key


; set blue HI as background color and palette 0 HI
	mov	dx, color_6845		; 3d9h
	mov	al, 00011001b
	out	dx, al
	mov	byte ptr ES:[COLOR_6845_BDA], al

        mov     dx, cursor_posi
	call	set_cursor
        mov     si, offset mode4_pal0h_dw_s
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset mode5_pal0h_dw_s
@@:
	call	print_str

	mov	dx, cursor_pos1
	call	set_cursor
	mov	si, offset pal0h_c1_str
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset color1h_str
@@:
	call	print_str

	mov	dx, cursor_pos2
	call	set_cursor
	mov	si, offset pal0h_c2_str
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset color2h_str
@@:
	call	print_str

	mov	dx, cursor_pos3
	call	set_cursor
	mov	si, offset pal0h_c3_str
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset color3h_str
@@:
	call	print_str
	call	wait_key


; set black as background color and palette 1
	mov	dx, color_6845		; 3d9h
	mov	al, 00100000b
	out	dx, al
	mov	byte ptr ES:[COLOR_6845_BDA], al

        mov     dx, cursor_posi
	call	set_cursor
	mov	si, offset mode4_pal1_dw_s
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset mode5_pal1_dw_s
@@:
        call    print_str

	mov	dx, cursor_pos0
	call	set_cursor
	mov	si, offset back_black_str
	call	print_str

	mov	dx, cursor_pos1
	call	set_cursor
	mov	si, offset pal1_c1_str
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset color1_str
@@:
	call	print_str

	mov	dx, cursor_pos2
	call	set_cursor
	mov	si, offset pal1_c2_str
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset color2_str
@@:
	call	print_str

	mov	dx, cursor_pos3
	call	set_cursor
	mov	si, offset pal1_c3_str
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset color3_str
@@:
	call	print_str
	call	wait_key


; set blue as background color and palette 1
	mov	dx, color_6845		; 3d9h
	mov	al, 00100001b
	out	dx, al
	mov	byte ptr ES:[COLOR_6845_BDA], al

	mov	dx, cursor_pos0
	call	set_cursor
	mov	si, offset back_blue_str
	call	print_str
	call	wait_key


; set blue HI as background color and palette 1
	mov	dx, color_6845		; 3d9h
	mov	al, 00101001b
	out	dx, al
	mov	byte ptr ES:[COLOR_6845_BDA], al

	mov	dx, cursor_pos0
	call	set_cursor
	mov	si, offset back_blueh_str
	call	print_str
	call	wait_key


; set blue HI as background color and palette 1 HI
	mov	dx, color_6845		; 3d9h
	mov	al, 00111001b
	out	dx, al
	mov	byte ptr ES:[COLOR_6845_BDA], al

        mov     dx, cursor_posi
	call	set_cursor
        mov     si, offset mode4_pal1h_dw_s
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset mode5_pal1h_dw_s
@@:
	call	print_str

	mov	dx, cursor_pos1
	call	set_cursor
	mov	si, offset pal1h_c1_str
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset color1h_str
@@:
	call	print_str

	mov	dx, cursor_pos2
	call	set_cursor
	mov	si, offset pal1h_c2_str
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset color2h_str
@@:
	call	print_str

	mov	dx, cursor_pos3
	call	set_cursor
	mov	si, offset pal1h_c3_str
	cmp	byte ptr set_video_mode, 04
	je     @F
	mov	si, offset color3h_str
@@:
	call	print_str
	call	wait_key

        mov     ah, 00h
	mov	al, init_video_mode	; return old video mode
	int	10h
        call    sync_fix        ; ??? for G3101

	retn
mode45 endp

;**********************Write screen for CGA mode 06***************************
; mode in AL
mode6 proc near
	mov	ah, 00h		; set mode function
	mov	set_video_mode, al
	int	10h

	mov	ah, 0Ch		; write point function
	mov	al, CGA_WHITE
	mov	cx, 00h		; column
	mov	dx, 00h		; row

mode6_loop:
 	push	ax
	int	10h
	pop	ax
	inc	cx
        cmp     cx, 640
	jne	mode6_loop
	mov	cx, 00h
	inc	dx

	cmp	dx, 20
	jne	@F
	mov	dx, 40
@@:
	cmp	dx, 60
	jne	@F
	mov	dx, 80
@@:
	cmp	dx, 100
	jne	@F
	mov	dx, 120
@@:
	cmp	dx, 140
	jne	@F
	mov	dx, 160
@@:
	cmp	dx, 180
	jb	mode6_loop

; print string
        mov     dx, 0000h
	call	set_cursor
        mov     si, offset mode6_s
        call    print_str
	call	wait_key

	mov     bh, 00h
	mov     bl, 00000010b   ; set green as forefround color
	mov	ah, 0Bh
	int     10h
; print string
	mov     dx, 0000h
	call    set_cursor
	mov     si, offset mode6_green_s
	call    print_str
	call    wait_key

	mov     bh, 00h
	mov     bl, 00001010b   ; set geen HI as foreground color
	mov	ah, 0Bh
	int     10h
; print string
	mov     dx, 0000h
	call    set_cursor
	mov     si, offset mode6_green_hi_s
	call    print_str
	call	wait_key

;----------------same mode6 test, but with direct I/O-----------------------
; 640x200
; bit0 set blue  foreground color
; bit1 set green foreground color
; bit2 set red   foreground color
; bit3 set intensity for foreground's colors
; bit4 set intensity colors
; bit5 - set palette  (N/A in this mode)
; bit6 - not used
; bit7 - not used

; set white HI as foreground color
	mov	ax, 0040h
	mov	es, ax			; ES > BDA segment
	mov	dx, color_6845		; 3d9h
	mov	al, 00001111b
	out	dx, al
	mov	byte ptr ES:[COLOR_6845_BDA], al

 ; write point
        mov     ax, CGA_VBUF_SEG
        mov     es, ax
        mov     al, 0ffh	; init color 0
        mov     si, 00000h	; mem addr for even rows
	mov	di, 02000h	; mem addr for odd rows

mode6d_loop:
        mov     byte ptr es:[si], al
	mov     byte ptr es:[di], al
        inc     si
	inc	di
        cmp     si, 800          ; 100str / 10 = 10
	jne	@F		 ; 10*640/8=800
	xor	al, 0ffh
@@:
        cmp     si, 1600
	jne	@F
	xor	al, 0ffh
@@:
	cmp	si, 2400
	jne	@F
	xor	al, 0ffh
@@:
	cmp	si, 3200
	jne	@F
	xor	al, 0ffh
@@:
	cmp	si, 4000
	jne	@F
	xor	al, 0ffh
@@:
	cmp	si, 4800
	jne	@F
	xor	al, 0ffh
@@:
	cmp	si, 5600
	jne	@F
	xor	al, 0ffh
@@:
	cmp	si, 6400
	jne	@F
	xor	al, 0ffh
@@:
	cmp	si, 7200
	jne	@F
	xor	al, 0ffh
@@:
	cmp	si, 8000
	jb	mode6d_loop

; print string
        mov     dx, 0000h
	call	set_cursor
        mov     si, offset mode6_dw_s
        call    print_str
	call	wait_key

; set green as foreground color
	mov	dx, color_6845
	mov     al, 00000010b
	out	dx, al
; print string
	mov     dx, 0000h
	call	set_cursor
	mov	si, offset mode6_green_dw_s
	call	print_str
	call	wait_key

; set green HI as foreground color
	mov	dx, color_6845
	mov     al, 00001010b
	out	dx, al
; print string
	mov     dx, 0000h
	call    set_cursor
	mov     si, offset mode6_green_dw_hi_s
	call    print_str
	call	wait_key


        mov     ah, 00h
	mov	al, init_video_mode	; return old video mode
	int	10h
        call    sync_fix        ; ??? for G3101

	retn
mode6 endp

;-----------------------------------------------------------------------
exit:
        mov     ax, 4C00h
	int	21h
main	endp

;********************get file name from cmd string*********************
get_cmd_fname proc near
; cmd symbols in es:si
        inc     cx	; add 1 to cmd string lenght for correct parsing
			; if only SPACE/TAB in CMD string, like "CT H "
gf_loop:
        lods    byte ptr es:[si]	; load new symbol
	cmp	al, ' '			; if space or TAB (09h), loop
	je	@F
	cmp	al, 09h		; 09h - TAB code
@@:
        loope   gf_loop

	cmp	al, 0Dh		; if 0Dh exit
	jne	@F
	retn
@@:
	cmp	al, 0		; if 0 exit
	jne	@F
	retn

@@:
	push	es
	push	ds

	push	es
	pop	ds		; DS ->PSP
	mov	bx, data
	mov	es, bx		; ES->DATA

	dec	si
	cmp	cx, 12
	jbe	@F
	mov	cx, 12		; max (8 + dot + 3)
@@:
        lea     di, h_bmp_file_s
gf_loop2:	
	lods	byte ptr ds:[si]
	cmp	al, ' '		; if space or TAB (09h), write 0 to end of file name
	je	@F
	cmp	al, 09h		; 09h - TAB code
	je	@F
	cmp	al, 0Dh		; if 0Dh exit
	je	@F
	stos	byte ptr es:[di]
	loop	gf_loop2
@@:
	mov	byte ptr es:[di], 0

gf_exit:
	pop	ds
	pop	es
	retn
get_cmd_fname endp
code	ends

if MEM_REALLOC
;--------------------------------------------------------------------------
zseg	segment para 'zseg'
zseg    ends

;--------------------------------------------------------------------------
endif

end	main		;end program
